import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local';

import Header from "./_components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: './_fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${inter.className} ${pretendard.className}`}>
        <Header />
        {children}</body>
    </html>
  );
}
